/**
 * Build Tweepcred Manager for dual console + Greasemonkey use.
 *
 * Concatenates modular sources into a single IIFE that works when:
 *   1. Pasted into the browser console on x.com
 *   2. Installed as a userscript (Tampermonkey / Violentmonkey / Greasemonkey)
 *
 * Usage:  node scripts/build.js
 * Output: dist/tweepcred-manager.user.js  (install / paste)
 *         tweepcredmanager.js             (back-compat root entry)
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const src = path.join(root, 'src');
const modulesDir = path.join(src, 'modules');

const ORDER = [
  path.join(src, 'header.meta.js'),
  path.join(src, 'bootstrap.js'),
  // Modules (shared scope inside the IIFE)
  path.join(modulesDir, 'core.js'),
  path.join(modulesDir, 'follow.js'),
  path.join(modulesDir, 'ui.js'),
  path.join(modulesDir, 'dashboard.js'),
  path.join(modulesDir, 'unfollow.js'),
  path.join(modulesDir, 'cleanup.js'),
  path.join(modulesDir, 'followers.js'),
  path.join(modulesDir, 'antibot.js'),
  path.join(modulesDir, 'about.js'),
  path.join(src, 'boot.js'),
  path.join(src, 'footer.js'),
];

function read(p) {
  if (!fs.existsSync(p)) {
    throw new Error('Missing source file: ' + p);
  }
  return fs.readFileSync(p, 'utf8').replace(/\r\n/g, '\n');
}

const parts = ORDER.map((p, i) => {
  const body = read(p).trimEnd();
  // The userscript block must be the very first thing in the file — some
  // script managers won't parse a header that starts below other comments.
  if (i === 0) return body + '\n';
  return '\n/* ---- ' + path.relative(root, p).replace(/\\/g, '/') + ' ---- */\n' + body + '\n';
});

const banner =
  '/*\n' +
  ' * AUTO-GENERATED by scripts/build.js — do not edit this file directly.\n' +
  ' * Edit sources under src/ and run: node scripts/build.js\n' +
  ' * Built: ' + new Date().toISOString() + '\n' +
  ' */\n';

// header.meta.js already has the userscript block; keep it first without banner above it
const header = parts[0];
const rest = parts.slice(1).join('');
const out = header.trimStart() + '\n' + banner + rest;

const distDir = path.join(root, 'dist');
fs.mkdirSync(distDir, { recursive: true });

const distPath = path.join(distDir, 'tweepcred-manager.user.js');
const compatPath = path.join(root, 'tweepcredmanager.js');

fs.writeFileSync(distPath, out);
fs.writeFileSync(compatPath, out);

console.log('Built:');
console.log('  ' + path.relative(root, distPath) + ' (' + out.length + ' bytes)');
console.log('  ' + path.relative(root, compatPath) + ' (compat copy)');
console.log('Modules concatenated:', ORDER.length);
